<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="MavenJenkinsSuite" duration-ms="11965" started-at="2016-10-01T01:56:18Z" finished-at="2016-10-01T01:56:30Z">
    <groups>
    </groups>
    <test name="MavenTest" duration-ms="11965" started-at="2016-10-01T01:56:18Z" finished-at="2016-10-01T01:56:30Z">
      <class name="com.pack.MavenJenkinsTestCase">
        <test-method status="PASS" signature="setUP()[pri:0, instance:com.pack.MavenJenkinsTestCase@23ceabc1]" name="setUP" is-config="true" duration-ms="10190" started-at="2016-10-01T07:26:18Z" finished-at="2016-10-01T07:26:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method status="FAIL" signature="firstTestCase()[pri:0, instance:com.pack.MavenJenkinsTestCase@23ceabc1]" name="firstTestCase" duration-ms="402" started-at="2016-10-01T07:26:28Z" finished-at="2016-10-01T07:26:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.pack.MavenJenkinsTestCase.firstTestCase(MavenJenkinsTestCase.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstTestCase -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.pack.MavenJenkinsTestCase@23ceabc1]" name="tearDown" is-config="true" duration-ms="1343" started-at="2016-10-01T07:26:28Z" finished-at="2016-10-01T07:26:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.pack.MavenJenkinsTestCase -->
    </test> <!-- MavenTest -->
  </suite> <!-- MavenJenkinsSuite -->
</testng-results>
